version: '3.8'

services:
  vue-nginx:
    build:
      context: .
    ports:
      - "8088:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /usr/share/nginx/html
    stdin_open: true
    tty: true